spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

coindesk:
  currentprice:
    url: https://api.coindesk.com/v1/bpi/currentprice.json




# enable/disable https
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: coindesk
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-password: changeit
    key-store-password: changeit

#spring:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: none

